# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

users = User.create!(
  [
    {name: 'もなか', email: 'monaka@test.com', password: 'Password01', password_confirmation: 'Password01', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user1.jpg"), filename:"sample-user1.jpg")},
    {name: 'ポテゴン', email: 'potegon@test.com', password: 'Password02', password_confirmation: 'Password02', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user2.jpg"), filename:"sample-user2.jpg")},
    {name: 'たけのこニョッキーン', email: 'takenoko@test.com', password: 'Password03', password_confirmation: 'Password03', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user3.jpg"), filename:"sample-user3.jpg")},
    {name: 'チョコ', email: 'choko@test.com', password: 'Password04', password_confirmation: 'Password04', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user4.jpg"), filename:"sample-user4.jpg")},
    {name: 'ぼってぃー', email: 'botthi@test.com', password: 'Password05', password_confirmation: 'Password05', image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-user5.jpg"), filename:"sample-user5.jpg")}
  ]
)

plans = Plan.create!(
  [
    {title: '沖縄旅行1日目 那覇', travel: 46, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-plan1.jpg"), filename:"sample-plan1.jpg"), user_id: users[0].id },
    {title: '沖縄旅行2日目 那覇', travel: 46, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-plan2.jpg"), filename:"sample-plan2.jpg"), user_id: users[0].id },
    {title: '沖縄旅行3日目 那覇と宮古島', travel: 46, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-plan3.jpg"), filename:"sample-plan3.jpg"), user_id: users[0].id },
    {title: '沖縄旅行4日目 宮古島', travel: 46, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-plan4.jpg"), filename:"sample-plan4.jpg"), user_id: users[0].id },
    {title: '沖縄旅行5日目 宮古島', travel: 46, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-plan5.jpg"), filename:"sample-plan5.jpg"), user_id: users[0].id },
    {title: '明太子を食べに福岡へ', travel: 39, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-plan6.jpg"), filename:"sample-plan6.jpg"), user_id: users[1].id },
    {title: '海鮮といえば築地', travel: 12, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-plan7.jpg"), filename:"sample-plan7.jpg"), user_id: users[2].id },
    {title: '名古屋ぶらり旅', travel: 22, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-plan8.jpg"), filename:"sample-plan8.jpg"), user_id: users[4].id }
  ]
)

contents = Content.create!(
  [
    {order: '1', hour: '11', minute: '20', place: '羽田空港出発', explanation: 'とても使いやすい空港。いつもきれいでレストランはどこもおいしい。', name: '東京国際空港', address: '〒144-0041 東京都大田区羽田空港', telephonenumber: '03-5757-8111', access: '実家から車で約2時間', businesshours: '5:00～24:00', price: '飛行機代によって変わる', stay_time: '約2時間', reservation: '完全予約制', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content1.jpg"), filename:"sample-content1.jpg"), plan_id: plans[0].id },
    {order: '2', hour: '14', minute: '20', place: '那覇空港到着', explanation: '沖縄の玄関口だけあってとてもきれい!', name: '那覇空港', address: '〒901-0142 沖縄県那覇市鏡水150', telephonenumber: '098-840-1151', access: '羽田から飛行機で約2時間', businesshours: '6:00～24:00', price: '飛行機代によって変わる', stay_time: '約1時間', reservation: '完全予約制', rate: 4.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content2.jpg"), filename:"sample-content2.jpg"), plan_id: plans[0].id },
    {order: '3', hour: '15', minute: '30', place: 'オリックスレンタカーで車を借りる', explanation: '那覇空港からマイクロバスが出ているからそれに乗ればお店まで行けます。', name: 'オリックスレンタカー那覇空港会員店', address: '〒901-0143 沖縄県那覇市安次嶺14-5', telephonenumber: '098-859-3900', access: '那覇空港からマイクロバスで約30分', businesshours: '8:00～20:00', price: '1日約1万円', stay_time: '約30分', reservation: '予約する方がよい', rate: 3, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content3.jpg"), filename:"sample-content3.jpg"), plan_id: plans[0].id },
    {order: '4', hour: '16', minute: '00', place: '首里城', explanation: '火災により建物など焼失してしまった。現在は復興中だが、首里城の上から見る景色はとてもきれい。', name: '首里城', address: '〒903-0815 沖縄県那覇市首里金城町1-2', telephonenumber: '098-886-2020', access: 'オリックスレンタカーから車で約30分', businesshours: '8:30～18:00', price: '入場料金400円', stay_time: '約1時間', reservation: '予約しなくてもよい', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content4.jpg"), filename:"sample-content4.jpg"), plan_id: plans[0].id },
    {order: '5', hour: '17', minute: '10', place: '国際通りで晩御飯とお土産', explanation: '御飯屋さんもお土産屋さんもたくさんある。あとドンキもあります。車は近くのパーキングに駐車しました。', name: '国際通り', address: '沖縄県那覇市牧志3丁目', telephonenumber: '098-863-2755', access: '首里城から車で約10分', businesshours: '各店舗により異なる（だいたい9:00～22:00）', price: '晩御飯とお土産で約1万円', stay_time: '約3時間', reservation: '予約しなくてもよい', rate: 4.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content5.jpg"), filename:"sample-content5.jpg"), plan_id: plans[0].id },
    {order: '1', hour: '10', minute: '30', place: '万座毛', explanation: '天然の海岸線は、美しい夕陽を望めるスポットとしても人気です。', name: '万座毛', address: '〒904-0401 沖縄県国頭郡恩納村字恩納', telephonenumber: '098-966-8080', access: 'ホテルモントレから車で約15分', businesshours: '8:00～20:00', price: '100円', stay_time: '約30分', reservation: '予約しなくてもよい', rate: 3.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content6.jpg"), filename:"sample-content6.jpg"), plan_id: plans[1].id },
    {order: '2', hour: '11', minute: '30', place: 'でいご家で沖縄そば', explanation: '軟骨ソーキそば（中）がおすすめです。', name: '沖縄そば でいご家', address: '〒905-0026 沖縄県名護市喜瀬197', telephonenumber: '0980-53-0222', access: '万座毛から車で約30分', businesshours: '年中無休 11:00～21:00', price: '約1000円', stay_time: '約30分', reservation: '予約しなくてもよい', rate: 3.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content7.jpg"), filename:"sample-content7.jpg"), plan_id: plans[1].id },
    {order: '3', hour: '12', minute: '50', place: '古宇利大橋南詰展望所', explanation: '海の絶景で有名な2島をつなぐ、現代的な橋です。', name: '古宇利大橋南詰展望所', address: '〒905-1635 沖縄県名護市済井出', telephonenumber: '不明', access: 'でいご家から車で約30分', businesshours: '24時間営業', price: '無料', stay_time: '約10分', reservation: '予約不可', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content8.jpg"), filename:"sample-content8.jpg"), plan_id: plans[1].id },
    {order: '4', hour: '13', minute: '10', place: 'ハートロック', explanation: 'ハート型をしたサンゴ岩。島の沖合にある写真スポット。', name: 'ティーヌ浜 ハートロック', address: '〒905-0406 沖縄県国頭郡今帰仁村古宇利2', telephonenumber: '不明', access: '古宇利大橋から車で約10分', businesshours: '24時間営業', price: '無料', stay_time: '約30分', reservation: '予約不可', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content9.jpg"), filename:"sample-content9.jpg"), plan_id: plans[1].id },
    {order: '5', hour: '14', minute: '10', place: 'フクギ並木', explanation: '樹齢数百年のフクギの木が並ぶ砂の道。サイクリングや牛車乗りが人気です。', name: '備瀬のフクギ並木', address: '〒905-0207 沖縄県国頭郡本部町備瀬389', telephonenumber: '0980-47-3641', access: 'ハートロックから車で約30分', businesshours: '24時間営業', price: 'サイクリングは1時間あたり約500円', stay_time: '約40分', reservation: '予約しなくてもよい', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content10.jpg"), filename:"sample-content10.jpg"), plan_id: plans[1].id },
    {order: '6', hour: '15', minute: '00', place: '美ら海水族館', explanation: '目の前に広がる美しい沖縄の海を満喫できるスポットです。サンゴ礁や深海など、さまざまな表情を見せる沖縄の海を余すことなく楽しめるのは、この水族館だけ！沖縄の海を満喫したいなら、外せないスポットです。', name: '沖縄美ら海水族館', address: '〒905-0206 沖縄県国頭郡本部町石川424', telephonenumber: '0980-48-3748', access: 'フクギ並木から車で約10分', businesshours: '8:30～18:30', price: '入場料金1880円', stay_time: '約2時間', reservation: '予約しなくてもよい', rate: 5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content11.jpg"), filename:"sample-content11.jpg"), plan_id: plans[1].id },
    {order: '1', hour: '8', minute: '30', place: 'BB-Coffeeでモーニング', explanation: '朝食の時間帯には、ドリンクを頼むと簡単な朝食が付きます。', name: 'BB-Coffee', address: '〒904-2172 沖縄県沖縄市泡瀬3丁目12−12', telephonenumber: '098-989-7212', access: 'ホテルモントレから車で約30分', businesshours: '7:00～17:00 水曜定休', price: '約1000円', stay_time: '約1時間', reservation: '予約しなくてもよい', rate: 4.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content12.jpg"), filename:"sample-content12.jpg"), plan_id: plans[2].id },
    {order: '2', hour: '10', minute: '00', place: 'アメリカンビレッジ', explanation: 'アメリカ合衆国の雰囲気を模したショッピング、エンターテイメントエリアです。', name: '美浜タウンリゾート・アメリカンビレッジ', address: '〒904-0115 沖縄県中頭郡北谷町美浜', telephonenumber: '098-926-5678', access: 'BB-Coffeeから車で約30分', businesshours: '10:00～22:00', price: '約2000円', stay_time: '約2時間', reservation: '予約しなくてもよい', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content13.jpg"), filename:"sample-content13.jpg"), plan_id: plans[2].id },
    {order: '3', hour: '13', minute: '30', place: 'レンタカーを返却し、那覇空港へ(宮古島に向かいます)', explanation: 'レンタカーを返す際は、ガソリン満タン給油を忘れずに！', name: '那覇空港', address: '〒901-0142 沖縄県那覇市鏡水150', telephonenumber: '098-840-1151', access: 'アメリカンビレッジから車で約1時間30分', businesshours: '6:00～24:00', price: '飛行機代によって変わる', stay_time: '約1時間', reservation: '完全予約制', rate: 4.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content14.jpg"), filename:"sample-content14.jpg"), plan_id: plans[2].id },
    {order: '4', hour: '15', minute: '20', place: '宮古島到着', explanation: '周りにいるお客さんを眺めたら、そこは沖縄宮古島の世界。', name: '宮古空港', address: '〒906-0013 沖縄県宮古島市平良下里1657−128', telephonenumber: '0980-72-1212', access: '那覇空港から飛行機で約1時間', businesshours: '6:00～24:00', price: '飛行機代によって変わる', stay_time: '約1時間', reservation: '完全予約制', rate: 4.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content15.jpg"), filename:"sample-content15.jpg"), plan_id: plans[2].id },
    {order: '5', hour: '16', minute: '30', place: 'オリックスレンタカーで車を借りる', explanation: '宮古空港からマイクロバスが出ているからそれに乗ればお店まで行けます。', name: 'オリックスレンタカー 宮古島', address: '〒906-0012 沖縄県宮古島市平良西里1332-3', telephonenumber: '0980-73-5500', access: '宮古空港からマイクロバスで約30分', businesshours: '8:00～19:00', price: '1日約1万円', stay_time: '約30分', reservation: '予約する方がよい', rate: 3, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content16.jpg"), filename:"sample-content16.jpg"), plan_id: plans[2].id },
    {order: '6', hour: '16', minute: '40', place: 'ジュース屋うる', explanation: '地元のフルーツや野菜がふんだんに使われ、水などでかさまししていない為かなり濃厚です。', name: '宮古島ジュース屋うる', address: '〒906-0000 沖縄県宮古島市平良西仲宗根3-3', telephonenumber: '080-3953-0141', access: 'オリックスレンタカーから車で約10分', businesshours: '13:00～17:00', price: '約1000円', stay_time: '約20分', reservation: '予約しなくてもよい', rate: 4.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content17.jpg"), filename:"sample-content17.jpg"), plan_id: plans[2].id },
    {order: '1', hour: '8', minute: '30', place: 'カフェ ニュイスでモーニング', explanation: '店内は手前に物販商品やスイーツを販売しており、奥にカフェスペースがあります。ゆとりある席配置で、窓からは広がる緑。のどかな雰囲気です。', name: '宮古島 カフェ ニュイス(cafe nuis)', address: '〒906-0103 沖縄県宮古島市城辺字 福里652番地2', telephonenumber: '0980-77-2154', access: 'ホテルから車で約30分', businesshours: '7:30～16:00 木、金曜定休', price: '約1000円', stay_time: '約1時間', reservation: '予約しなくてもよい', rate: 4.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content18.jpg"), filename:"sample-content18.jpg"), plan_id: plans[3].id },
    {order: '2', hour: '9', minute: '50', place: '東平安名崎', explanation: '見晴台から見る景色は最高です。でも、階段を上り下りするのが大変です。', name: '東平安名崎', address: '〒906-0000 沖縄県宮古島市城辺保良1221-14', telephonenumber: '0980-77-4905', access: 'カフェニュイスから車で約15分', businesshours: '24時間営業', price: '300円', stay_time: '約1時間', reservation: '予約不可', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content19.jpg"), filename:"sample-content19.jpg"), plan_id: plans[3].id },
    {order: '3', hour: '11', minute: '10', place: '池間大橋', explanation: '伊良部大橋と青い海が非常に美しく見えるスポットです。', name: '池間大橋', address: '〒906-0421 沖縄県宮古島市平良池間', telephonenumber: '不明', access: '東平安名崎から車で約40分', businesshours: '24時間営業', price: '無料', stay_time: '約10分', reservation: '予約不可', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content20.jpg"), filename:"sample-content20.jpg"), plan_id: plans[3].id },
    {order: '4', hour: '11', minute: '30', place: 'ハート岩', explanation: 'とてもわかりづらいです。ただとても海がきれいです。', name: 'ハート岩', address: '〒906-0000 沖縄県宮古島市平良池間 宮古市', telephonenumber: '不明', access: '池間大橋から車で約10分', businesshours: '24時間営業', price: '無料', stay_time: '約30分', reservation: '予約不可', rate: 3.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content21.jpg"), filename:"sample-content21.jpg"), plan_id: plans[3].id },
    {order: '5', hour: '12', minute: '30', place: '伊良部大橋', explanation: '宮古島と伊良部島とを結ぶ橋で全長3,540メートルあります。長い！', name: '伊良部大橋', address: '〒906-0000 沖縄県宮古島市', telephonenumber: '不明', access: 'ハート岩から車で約30分', businesshours: '24時間営業', price: '無料', stay_time: '約10分', reservation: '予約不可', rate: 3.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content22.jpg"), filename:"sample-content22.jpg"), plan_id: plans[3].id },
    {order: '6', hour: '12', minute: '50', place: 'ブルータートル（カフェ）', explanation: 'カレーがおいしかったです。店員さんがちょっと怖かったです。', name: 'ブルータートル[Blue Turtle]', address: '〒906-0503 沖縄県宮古島市伊良部伊良部1352-16', telephonenumber: '0980-74-5333', access: '伊良部大橋から車で約20分', businesshours: '11:00～22:00', price: '約1500円', stay_time: '約1時間', reservation: '予約しなくてもよい', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content23.jpg"), filename:"sample-content23.jpg"), plan_id: plans[3].id },
    {order: '7', hour: '13', minute: '50', place: '渡口の浜', explanation: 'ブルータートルの目の前の海なので、ブルータートルでご飯を食べたらそのまま歩いて行けます。', name: '渡口の浜', address: '〒906-0503 沖縄県宮古島市伊良部伊良部1352-16', telephonenumber: '不明', access: 'ブルータートルから歩いて1分', businesshours: '24時間営業', price: '無料', stay_time: '約30分', reservation: '予約不可', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content24.jpg"), filename:"sample-content24.jpg"), plan_id: plans[3].id },
    {order: '8', hour: '14', minute: '40', place: 'なかゆくい商店でサーターアンダギー', explanation: '紅芋サーターアンダギーにアイスをトッピングをするとさらにおいしいです。', name: 'なかゆくい商店', address: '〒906-0505 沖縄県宮古島市伊良部国仲57-3', telephonenumber: '090-9476-3215', access: '渡口の浜から車で10分', businesshours: '9:30～16:00', price: '約1000円', stay_time: '約30分', reservation: '予約しなくてもよい', rate: 4.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content25.jpg"), filename:"sample-content25.jpg"), plan_id: plans[3].id },
    {order: '9', hour: '15', minute: '10', place: '17ENDビーチ', explanation: 'とにかくきれい。まっすぐ伸びる道はかなり長いのでレンタサイクルするのもありです。', name: '17ENDビーチ', address: '〒906-0507 沖縄県宮古島市伊良部佐和田', telephonenumber: '不明', access: 'なゆくい商店から車で10分', businesshours: '24時間営業', price: '無料', stay_time: '約30分', reservation: '予約不可', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content26.jpg"), filename:"sample-content26.jpg"), plan_id: plans[3].id },
    {order: '10', hour: '16', minute: '10', place: 'イグアナ岩', explanation: '崖の上から眺めるエメラルドグリーンの海はめちゃくちゃ美しかったです。しかし、一歩間違えると崖から落ちる可能性があるので行く際は十分に注意してください。', name: 'イグアナ岩', address: '〒906-0501 沖縄県宮古島市伊良部前里添', telephonenumber: '不明', access: '17ENDビーチから車で20分', businesshours: '24時間営業', price: '無料', stay_time: '約30分', reservation: '予約不可', rate: 5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content27.jpg"), filename:"sample-content27.jpg"), plan_id: plans[3].id },
    {order: '11', hour: '17', minute: '10', place: '来間大橋', explanation: '伊良部大橋や池間大橋に比べて短いですが、その分来間島が間近に見えて、島と橋が調和して見えます。', name: '来間大橋', address: '〒906-0000 沖縄県宮古島市', telephonenumber: '不明', access: 'イグアナ岩から車で30分', businesshours: '24時間営業', price: '無料', stay_time: '約30分', reservation: '予約不可', rate: 3.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content28.jpg"), filename:"sample-content28.jpg"), plan_id: plans[3].id },
    {order: '12', hour: '18', minute: '30', place: '花風で晩御飯', explanation: 'とても優しいおばあちゃんが一人でやっている。ナポリタンが絶品。花風に来たら絶対に食べてほしいです。', name: '花風', address: '〒906-0306 沖縄県宮古島市下地来間130', telephonenumber: '080-2259-8238', access: '来間大橋から車で30分', businesshours: '11:30～14:00、18:30～23:00', price: '約1000円', stay_time: '約1時間', reservation: '予約しなくてもよい', rate: 5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content29.jpg"), filename:"sample-content29.jpg"), plan_id: plans[3].id },
    {order: '1', hour: '8', minute: '30', place: 'ウェディングフォト撮影', explanation: '最初は曇っていたが、だんだんと晴れてきて良い写真がとれた。また、カメラマンさん達はみんなよい人ばかりで撮影がとても楽しかった。宮古島でウェディングフォトを撮るならcapryフォトウェディング宮古島さんをおすすめします。', name: 'capryフォトウェディング宮古島', address: '〒906-0013 沖縄県宮古島市平良字下里356-118', telephonenumber: '0078-6009-6649', access: 'ホテルから車で30分', businesshours: '10:00～18:00 年末年始は休み', price: '約12万円', stay_time: '約6時間', reservation: '完全予約制', rate: 5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content30.jpg"), filename:"sample-content30.jpg"), plan_id: plans[4].id },
    {order: '2', hour: '14', minute: '30', place: '古謝そばを食べて飛行機乗って帰宅', explanation: '宮古島の人気店で、結構並んでました。宮古そばセットを100円+でソーキそばセットに変えました。', name: '古謝そば屋', address: '〒906-0013 沖縄県宮古島市平良下里1517-1', telephonenumber: '0980-72-8304', access: 'capryから車で30分', businesshours: '11:00～16:00 水曜定休', price: '約1000円', stay_time: '約1時間', reservation: '予約しなくてもよい', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content31.jpg"), filename:"sample-content31.jpg"), plan_id: plans[4].id },
    {order: '1', hour: '12', minute: '30', place: '元祖博多めんたい重を食べるために福岡へ', explanation: 'とにかく行列がすごく、1時間半くらい並びました。長時間待った後のめんたい重は格別です。', name: '元祖博多めんたい重', address: '〒810-0002 福岡県福岡市中央区西中洲6-15', telephonenumber: '092-725-7220', access: '群馬から飛行機と電車で約6時間', businesshours: '7:00～22:30', price: '約2000円', stay_time: '約2時間半', reservation: '予約不可', rate: 4.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content32.jpg"), filename:"sample-content32.jpg"), plan_id: plans[5].id },
    {order: '1', hour: '8', minute: '00', place: '築地で海鮮丼', explanation: 'やっぱり、海鮮丼は築地に限る。', name: '築地場外市場', address: '〒104-0045 東京都中央区築地4丁目16番2号', telephonenumber: '03-3541-9444', access: '自宅から車で2時間', businesshours: '8:00～14:00', price: '約2000円', stay_time: '約1時間半', reservation: '予約しなくてもよい', rate: 5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content33.jpg"), filename:"sample-content33.jpg"), plan_id: plans[6].id },
    {order: '2', hour: '12', minute: '30', place: '築地の帰りに小江戸横丁', explanation: '芋スイーツやドリンクにお酒がたくさんなので食べ歩きが好きな方にはおすすめです。', name: '小江戸横丁', address: '〒350-0062 埼玉県川越市元町2丁目1-3', telephonenumber: '不明', access: '築地から車で1時間半', businesshours: '9:00～17:00', price: '約2000円', stay_time: '約1時間半', reservation: '予約しなくてもよい', rate: 3.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content34.jpg"), filename:"sample-content34.jpg"), plan_id: plans[6].id },
    {order: '1', hour: '7', minute: '30', place: 'コーヒーハウス かこでモーニング', explanation: '名古屋といえばモーニング。朝から長蛇の列ができていました。', name: 'コーヒーハウス かこ 花車本店', address: '〒450-0002 愛知県名古屋市中村区名駅5丁目16-17', telephonenumber: '052-586-0239', access: 'ホテルから歩いて15分', businesshours: '7:00～19:00', price: '約1000円', stay_time: '約1時間半', reservation: '予約不可', rate: 4.5, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content35.jpg"), filename:"sample-content35.jpg"), plan_id: plans[7].id },
    {order: '2', hour: '10', minute: '30', place: 'トヨタ産業技術記念館', explanation: 'トヨタの歴史、自動織機と自動車の開発の歴史が楽しく学べる博物館です。', name: 'トヨタ産業技術記念館', address: '〒451-0051 愛知県名古屋市西区則武新町4丁目1-35', telephonenumber: '052-551-6115', access: 'ホテルから車で30分', businesshours: '9:30～17:00 月曜定休', price: '500円', stay_time: '約1時間半', reservation: '予約しなくてもよい', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content36.jpg"), filename:"sample-content36.jpg"), plan_id: plans[7].id },
    {order: '3', hour: '12', minute: '30', place: '東山動植物園', explanation: '広大な敷地 イケメン過ぎるゴリラ やる気の無い動物達 楽しい動物園でした。', name: '東山動植物園', address: '〒464-0804 愛知県名古屋市千種区東山元町3丁目70', telephonenumber: '052-782-2111', access: 'トヨタ産業技術記念館から車で30分', businesshours: '9:00～16:50 月曜定休', price: '500円', stay_time: '約1時間半', reservation: '予約しなくてもよい', rate: 4, image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sample-content37.jpg"), filename:"sample-content37.jpg"), plan_id: plans[7].id }
  ]
)

comments = Comment.create!(
  [
    {comment: '首里城はやく復興されるといいですね', plan_id: plans[0].id, user_id: users[1].id },
    {comment: 'ドンキがあるのは安心', plan_id: plans[0].id, user_id: users[2].id },
    {comment: 'レンタカーって高いよね', plan_id: plans[0].id, user_id: users[3].id },
    {comment: '沖縄いいな～', plan_id: plans[0].id, user_id: users[4].id },
    {comment: '万座毛の写真の人、陸で溺れてね？w', plan_id: plans[1].id, user_id: users[1].id },
    {comment: '完全に溺れてて草', plan_id: plans[1].id, user_id: users[2].id },
    {comment: 'どうやったら陸で溺れるん？', plan_id: plans[1].id, user_id: users[3].id },
    {comment: '陸で溺れるはおもろい', plan_id: plans[1].id, user_id: users[4].id },
    {comment: 'ドリンク買って朝食付くのいいね', plan_id: plans[2].id, user_id: users[1].id },
    {comment: 'アメリカンビレッジ行ってみたい', plan_id: plans[2].id, user_id: users[2].id },
    {comment: 'うるのジュースうまそ', plan_id: plans[2].id, user_id: users[3].id },
    {comment: '宮古島の海ってめっちゃきれいだよね', plan_id: plans[2].id, user_id: users[4].id },
    {comment: 'おばあちゃんのナポリタン食べたい', plan_id: plans[3].id, user_id: users[1].id },
    {comment: '花風のおばあちゃんめっちゃいい人だった', plan_id: plans[3].id, user_id: users[2].id },
    {comment: 'ナポリタン以外も普通にうまい', plan_id: plans[3].id, user_id: users[3].id },
    {comment: 'サーターアンダギーうまそ～', plan_id: plans[3].id, user_id: users[4].id },
    {comment: 'ウェディングフォトええね～', plan_id: plans[4].id, user_id: users[1].id },
    {comment: 'ウェディングフォトとか何年前やら・・・', plan_id: plans[4].id, user_id: users[2].id },
    {comment: '写真撮るだけで12万とか高くね？', plan_id: plans[4].id, user_id: users[3].id },
    {comment: '写真以外にも衣装とかデータ代も含まれていると思いますよ', plan_id: plans[4].id, user_id: users[4].id },
    {comment: '1時間半はえぐいな', plan_id: plans[5].id, user_id: users[0].id },
    {comment: 'おれは待てんわ', plan_id: plans[5].id, user_id: users[2].id },
    {comment: 'めんたい重うまそ～', plan_id: plans[5].id, user_id: users[3].id },
    {comment: 'めんたい重の為だけに行くなんて、相当うまいんだな', plan_id: plans[5].id, user_id: users[4].id },
    {comment: '築地行ったことない', plan_id: plans[6].id, user_id: users[0].id },
    {comment: '朝食に海鮮丼はいいね', plan_id: plans[6].id, user_id: users[1].id },
    {comment: '築地といえば卵焼き', plan_id: plans[6].id, user_id: users[3].id },
    {comment: '海鮮丼好き', plan_id: plans[6].id, user_id: users[4].id },
    {comment: 'モーニングに朝から並ぶのすご', plan_id: plans[7].id, user_id: users[0].id },
    {comment: '世界のトヨタ', plan_id: plans[7].id, user_id: users[1].id },
    {comment: 'イケメンのゴリラwww', plan_id: plans[7].id, user_id: users[2].id },
    {comment: '動物たちやる気だせ', plan_id: plans[7].id, user_id: users[3].id }
  ]
)